In [29]:
# !pip install scikit-learn
# !pip install pandas
# !pip install numpy

In [50]:
import sklearn
import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer 

In [51]:
data = load_breast_cancer()

# Подготовка данных

In [52]:
data_df = pd.DataFrame(data = data.data,
                       columns = data.feature_names) 
data_df

# data1 = pd.DataFrame(data= np.c_[data['data'], data['target']],
#                     columns= data['feature_names'] + ['target'])

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

0 - Malignant (Злокачественный)

1 - Benign (Доброкачественный)

In [53]:
data_df["target"] = data.target
data_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890       0  
1                  0.1860          0.2750                  0.08902       0  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.076

## Стандартизация

In [54]:
from sklearn.preprocessing import StandardScaler

In [55]:
scaler = StandardScaler()

scaler.fit(data_df.drop('target', axis=1))
scaled_features = scaler.transform(data_df.drop('target',
                                           axis=1))
 
df_feat = pd.DataFrame(scaled_features,
                       columns=data_df.columns[:-1])
df_feat.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                2.255747  ...      1.886690      -1.359293         2.303601   
1               -0.868652  ...      1.805927      -0.369203         1.535126   
2               -0.398008  ...      1.511870      -0.023974         1.347475   
3                4.910919  ...     -0.281464       0.133984        -0.249939   
4               -0.562450  ...      1.298575      -1.466770         1.338539   

   worst area  worst smoothness  worst compactness  worst concavity  \
0    2.001237          1.307686           2.616665         2.109526   
1    1.890489         -0.375612          -0.430444        -0.146749   
2    1.456285          0.527407           1.082932         0.854974   
3   -0.550021          3.394275           3.893397         1.989588   
4    1.220724          0.220556          -0.313395         0.613179   

   worst concave points  worst symmetry  worst fractal dimension  
0              2.296076        2.750622                 1.937015  
1              1.087084       -0.243890                 0.281190  
2              1.955000        1.152255                 0.201391  
3              2.175786        6.046041                 4.935010  
4              0.729259       -0.868353                -0.397100  

[5 rows x 30 columns]

### Проверка стандартизации
мат.ожидание = 0

дисперсия = 1

In [56]:
df_feat.mean()

mean radius               -3.162867e-15
mean texture              -6.530609e-15
mean perimeter            -7.078891e-16
mean area                 -8.799835e-16
mean smoothness            6.132177e-15
mean compactness          -1.120369e-15
mean concavity            -4.421380e-16
mean concave points        9.732500e-16
mean symmetry             -1.971670e-15
mean fractal dimension    -1.453631e-15
radius error              -9.076415e-16
texture error             -8.853492e-16
perimeter error            1.773674e-15
area error                -8.291551e-16
smoothness error          -7.541809e-16
compactness error         -3.921877e-16
concavity error            7.917900e-16
concave points error      -2.739461e-16
symmetry error            -3.108234e-16
fractal dimension error   -3.366766e-16
worst radius              -2.333224e-15
worst texture              1.763674e-15
worst perimeter           -1.198026e-15
worst area                 5.049661e-16
worst smoothness          -5.213170e-15


In [57]:
df_feat.std()

mean radius                1.00088
mean texture               1.00088
mean perimeter             1.00088
mean area                  1.00088
mean smoothness            1.00088
mean compactness           1.00088
mean concavity             1.00088
mean concave points        1.00088
mean symmetry              1.00088
mean fractal dimension     1.00088
radius error               1.00088
texture error              1.00088
perimeter error            1.00088
area error                 1.00088
smoothness error           1.00088
compactness error          1.00088
concavity error            1.00088
concave points error       1.00088
symmetry error             1.00088
fractal dimension error    1.00088
worst radius               1.00088
worst texture              1.00088
worst perimeter            1.00088
worst area                 1.00088
worst smoothness           1.00088
worst compactness          1.00088
worst concavity            1.00088
worst concave points       1.00088
worst symmetry      

# Прогноз с произвольным k

In [58]:
from sklearn.metrics import classification_report,\
    confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test,\
    y_train, y_test = train_test_split(scaled_features,
                                       data_df['target'],
                                       test_size=0.50, random_state=1)
 
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)
 
print("Confusion матрица:\n", confusion_matrix(y_test, pred)) # в scikit learn истинные - строки, предсказанные - столбцы

report = classification_report(y_test, pred, output_dict=True)
# print("\n", classification_report(y_test, pred)) 
for label in sorted(report.keys()):
    if label not in ["accuracy", "macro avg", "weighted avg"]:
        print(f"Класс {label}: {report[label]}")

Confusion матрица:
 [[ 93  10]
 [  7 175]]
Класс 0: {'precision': 0.93, 'recall': 0.9029126213592233, 'f1-score': 0.916256157635468, 'support': 103.0}
Класс 1: {'precision': 0.9459459459459459, 'recall': 0.9615384615384616, 'f1-score': 0.9536784741144414, 'support': 182.0}


# Подбор k
## GridSearchCV

In [60]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV

In [61]:
param_grid = {
    'n_neighbors': list(range(1, 50)), 
}

knn_cv = GridSearchCV(
            knn, 
            param_grid, 
            cv=5, 
            scoring='accuracy'
        )

In [62]:
knn_cv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30, ...]},
             scoring='accuracy')

In [63]:
print(f"Лучший параметр: {knn_cv.best_params_}")
print(f"Лучшая кросс-валидационная accuracy: {knn_cv.best_score_:.2f}")

Лучший параметр: {'n_neighbors': 3}
Лучшая кросс-валидационная accuracy: 0.99


## RandomSearchCV

In [64]:
from sklearn.model_selection import RandomizedSearchCV


knn = KNeighborsClassifier()


param_grid = {
    'n_neighbors': range(1, 50)   
}


random_search = RandomizedSearchCV(
    knn, 
    param_grid, 
    n_iter=10,  # Limit the number of iterations (10 combinations)
    cv=5,  # 5-fold cross-validation
    scoring='accuracy',  # You can use 'precision', 'recall', or 'f1' here for different use cases
    random_state=42
)

random_search.fit(X_train, y_train)

# Find the best parameters and score
print(f"Лучший параметр: {random_search.best_params_}")
print(f"Best cross-validated accuracy: {random_search.best_score_:.2f}")

# Evaluate the best model on the test set
best_knn = random_search.best_estimator_
test_accuracy = best_knn.score(X_test, y_test)

print(f"Лучший accuracy тестового сета: {test_accuracy:.2f}")

Лучший параметр: {'n_neighbors': 14}
Best cross-validated accuracy: 0.96
Лучший accuracy тестового сета: 0.93


## Кросс-валидация
### K-Fold

In [83]:
from sklearn.model_selection import StratifiedKFold, RepeatedStratifiedKFold, ShuffleSplit, cross_val_score

In [66]:
df_feat

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0       1.097064     -2.073335        1.269934   0.984375         1.568466   
1       1.829821     -0.353632        1.685955   1.908708        -0.826962   
2       1.579888      0.456187        1.566503   1.558884         0.942210   
3      -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4       1.750297     -1.151816        1.776573   1.826229         0.280372   
..           ...           ...             ...        ...              ...   
564     2.110995      0.721473        2.060786   2.343856         1.041842   
565     1.704854      2.085134        1.615931   1.723842         0.102458   
566     0.702284      2.045574        0.672676   0.577953        -0.840484   
567     1.838341      2.336457        1.982524   1.735218         1.525767   
568    -1.808401      1.221792       -1.814389  -1.347789        -3.112085   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0            3.283515        2.652874             2.532475       2.217515   
1           -0.487072       -0.023846             0.548144       0.001392   
2            1.052926        1.363478             2.037231       0.939685   
3            3.402909        1.915897             1.451707       2.867383   
4            0.539340        1.371011             1.428493      -0.009560   
..                ...             ...                  ...            ...   
564          0.219060        1.947285             2.320965      -0.312589   
565         -0.017833        0.693043             1.263669      -0.217664   
566         -0.038680        0.046588             0.105777      -0.809117   
567          3.272144        3.296944             2.658866       2.137194   
568         -1.150752       -1.114873            -1.261820      -0.820070   

     mean fractal dimension  ...  worst radius  worst texture  \
0                  2.255747  ...      1.886690      -1.359293   
1                 -0.868652  ...      1.805927      -0.369203   
2                 -0.398008  ...      1.511870      -0.023974   
3                  4.910919  ...     -0.281464       0.133984   
4                 -0.562450  ...      1.298575      -1.466770   
..                      ...  ...           ...            ...   
564               -0.931027  ...      1.901185       0.117700   
565               -1.058611  ...      1.536720       2.047399   
566               -0.895587  ...      0.561361       1.374854   
567                1.043695  ...      1.961239       2.237926   
568               -0.561032  ...     -1.410893       0.764190   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0           2.303601    2.001237          1.307686           2.616665   
1           1.535126    1.890489         -0.375612          -0.430444   
2           1.347475    1.456285          0.527407           1.082932   
3          -0.249939   -0.550021          3.394275           3.893397   
4           1.338539    1.220724          0.220556          -0.313395   
..               ...         ...               ...                ...   
564         1.752563    2.015301          0.378365          -0.273318   
565         1.421940    1.494959         -0.691230          -0.394820   
566         0.579001    0.427906         -0.809587           0.350735   
567         2.303601    1.653171          1.430427           3.904848   
568        -1.432735   -1.075813         -1.859019          -1.207552   

     worst concavity  worst concave points  worst symmetry  \
0           2.109526              2.296076        2.750622   
1          -0.146749              1.087084       -0.243890   
2           0.854974              1.955000        1.152255   
3           1.989588              2.175786        6.046041   
4           0.613179              0.729259       -0.868353   
..               ...                   ...             ...   
564         0.664512              1.629151       -1

In [85]:
X = df_feat
y = data_df['target'] 
kf = StratifiedKFold(n_splits=3)
for train, test in kf.split(X, y):
    print("%s %s" % (train, test))

[121 122 126 127 129 131 132 134 135 138 141 146 156 161 162 164 167 168
 171 172 177 180 181 182 184 186 190 193 194 196 197 198 199 201 202 203
 205 207 210 212 213 214 215 218 219 223 229 230 233 236 237 239 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279
 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297
 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315
 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333
 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351
 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369
 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387
 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405
 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423
 424 425 426 427 428 429 430 431 432 433 434 435 43

In [86]:
kf = StratifiedKFold(n_splits=5)
scores = cross_val_score(KNeighborsClassifier(n_neighbors=5), 
                         X, y, scoring='accuracy', 
                         cv=kf)
scores

array([0.96491228, 0.95614035, 0.98245614, 0.95614035, 0.96460177])

GridSearch scores

In [87]:
y = data_df['target']            
kf = StratifiedKFold(n_splits=5)
scores = cross_val_score(KNeighborsClassifier(n_neighbors=3), 
                         X, y, scoring='accuracy', 
                         cv=kf)
scores

array([0.97368421, 0.95614035, 0.98245614, 0.94736842, 0.92920354])

RandomSearch scores

In [88]:
y = data_df['target']            
kf = StratifiedKFold(n_splits=5)
scores = cross_val_score(KNeighborsClassifier(n_neighbors=14), 
                         X, y, scoring='accuracy', 
                         cv=kf)
scores

array([0.96491228, 0.93859649, 0.99122807, 0.95614035, 0.98230088])

### Repeated K-Fold

In [92]:
kf = RepeatedStratifiedKFold(n_splits=3, n_repeats=2)
for train, test in kf.split(X, y):
    print("%s %s" % (train, test))

[  1   2   3   5   6   7   8  10  11  12  13  14  19  20  22  24  25  27
  28  29  32  33  36  37  38  40  41  42  46  48  49  50  51  52  53  55
  57  58  59  60  61  62  63  64  67  69  71  72  73  75  76  77  79  80
  81  82  83  84  85  86  87  88  90  91  93  94  95  96  99 101 102 103
 104 106 107 112 113 115 116 117 118 119 120 121 122 123 125 126 127 130
 131 132 133 134 138 139 141 144 146 148 149 150 155 157 158 161 162 164
 165 168 170 171 172 173 175 176 179 181 182 183 187 188 189 191 192 193
 195 196 197 198 199 200 201 204 205 206 207 208 209 211 212 213 215 218
 219 221 223 227 228 229 230 233 234 236 237 238 241 245 246 247 249 250
 251 252 253 254 255 256 257 258 259 261 262 263 264 266 267 268 269 270
 272 273 274 275 277 278 281 283 285 287 288 290 291 293 294 295 298 299
 301 303 306 307 308 310 311 312 313 315 317 319 320 321 325 326 329 330
 331 332 333 334 335 336 338 339 341 342 344 345 346 347 348 349 350 352
 357 358 361 364 365 366 367 368 369 370 371 372 37

In [93]:
scores = cross_val_score(KNeighborsClassifier(n_neighbors=5), 
                         X, y, scoring='accuracy', 
                         cv=kf)
scores

array([0.96842105, 0.96315789, 0.96825397, 0.96842105, 0.96315789,
       0.96825397])

In [94]:
scores = cross_val_score(KNeighborsClassifier(n_neighbors=3), 
                         X, y, scoring='accuracy', 
                         cv=kf)
scores

array([0.96315789, 0.95789474, 0.97354497, 0.97894737, 0.96315789,
       0.96296296])

In [95]:
scores = cross_val_score(KNeighborsClassifier(n_neighbors=14), 
                         X, y, scoring='accuracy', 
                         cv=kf)
scores

array([0.96315789, 0.95789474, 0.96296296, 0.97894737, 0.93684211,
       0.96825397])

### Shuffle and split

In [78]:
kf = ShuffleSplit(n_splits=5, test_size=0.25)
for train, test in kf.split(X):
    print("%s %s" % (train, test))

[ 93 336  21 534 517 403 492 166   1 395 269  16 268  39 464  19 397 283
 151 202 448 446 308 568 545   3 358 175 320 541 356 375 416 505 235  71
 510  47 547  28 195 465 482 191  77 462 424 201 362 546 171  24 353 121
  12 170 381 372 234 387  38 183 552 215 295 550 332 480 506  35 441 221
 132 159 485 502 437 512 522 136 565 150 376  36 443 285 260 340  98 439
 253 255 525  72 390 544 564 112 240  49 535  26 263 226 193 324 228 563
 497 410 200 329 342 206 270 436 355 322  63 394 423 113 479 286 109 199
  66 328 346 162 312 274 452 498 212 475 251  25  88 530 473 261 288  31
 493 144 429 273 293  85  10 520 117 540 515 514 354  90 264 103 182 478
 509 469 538 305 449 402 504 301  13 145 542 304 339 311 135  40 116 366
 481 204 555 205 223 158 434 262 194 337 289 138 351 357 104  50 271 142
 406  81 494  46 444 178 399  91 384 389 105  83 197 122 447 388  56  32
 401 477 484  95 491  65  48 347 451 440 414 385 379 185 496 281  70 216
 315  78 219  76 420 391 466 157 405 335 257 421 21

In [96]:
scores = cross_val_score(KNeighborsClassifier(n_neighbors=5), 
                         X, y, scoring='accuracy', 
                         cv=kf)
scores

array([0.96842105, 0.95789474, 0.94708995, 0.95789474, 0.95789474,
       0.97354497])

In [97]:
scores = cross_val_score(KNeighborsClassifier(n_neighbors=3), 
                         X, y, scoring='accuracy', 
                         cv=kf)
scores

array([0.97368421, 0.97894737, 0.95767196, 0.96842105, 0.95789474,
       0.96825397])

In [98]:
scores = cross_val_score(KNeighborsClassifier(n_neighbors=14), 
                         X, y, scoring='accuracy', 
                         cv=kf)
scores

array([0.97368421, 0.93157895, 0.96825397, 0.95789474, 0.95789474,
       0.96296296])